require("scripts.packer")
require("scripts.set")
require("scripts.remap")
require("scripts.lsp")
require("scripts.treesitter")
require("scripts.autocomplete")
require("scripts.autopairs")
require("scripts.lualine")
require("scripts.lspsaga")
-- require("scripts.trouble")
require("scripts.lsp-colors")
